import { HighlightStyle } from '@codemirror/language'
import { EditorView } from '@codemirror/view'
import { tags } from '@lezer/highlight'

export const darkTheme = EditorView.theme(
  {
    '&': {
      backgroundColor: 'var(--bg-base)',
      color: 'var(--text)',
      height: '100%',
    },
    '.cm-content': {
      fontFamily: "'JetBrains Mono', 'Fira Code', monospace",
      fontSize: '14px',
      lineHeight: '1.8',
      padding: '20px 32px',
      caretColor: 'var(--caret)',
      maxWidth: '800px',
    },
    '.cm-cursor': { borderLeftColor: 'var(--caret)', borderLeftWidth: '2px' },
    '.cm-gutters': { display: 'none' },
    '.cm-selectionBackground, ::selection': {
      backgroundColor: 'var(--bg-active) !important',
    },
    '&.cm-focused .cm-selectionBackground': {
      backgroundColor: 'var(--bg-active2) !important',
    },
    '.cm-line': { padding: '0' },
    '.cm-blockquote': {
      borderLeft: '3px solid var(--accent)',
      paddingLeft: '16px',
    },
    '.cm-task-checkbox': {
      cursor: 'pointer',
      verticalAlign: 'middle',
      marginRight: '4px',
      accentColor: 'var(--accent)',
    },
    '.cm-wikilink, .cm-wikilink *': {
      color: 'var(--accent) !important',
    },
    '.cm-wikilink': {
      borderRadius: '4px',
      padding: '1px 4px',
      fontWeight: '500',
      cursor: 'pointer',
    },
    '.cm-mdlink': {
      color: 'var(--accent)',
      textDecoration: 'underline',
      textDecorationStyle: 'dotted',
      cursor: 'pointer',
    },
    '.cm-hr-widget': {
      display: 'block',
      height: '1px',
      background: 'var(--bg-active2)',
      backgroundClip: 'content-box',
      border: 'none',
      padding: '11px 0',
      width: '100%',
      boxSizing: 'content-box',
    },
    '.cm-table-widget-wrapper': {
      padding: '8px 0',
    },
    '.cm-table-widget': {
      borderCollapse: 'collapse',
      width: '100%',
      fontSize: '14px',
    },
    '.cm-table-widget th, .cm-table-widget td': {
      border: '1px solid var(--border-2)',
      padding: '4px 12px',
      textAlign: 'left',
      color: 'var(--text)',
    },
    '.cm-table-widget thead': {
      background: 'var(--bg-surface)',
    },
    '.cm-table-widget thead th': {
      color: 'var(--accent-2)',
      fontWeight: 'bold',
    },
    '.cm-fenced-top': {
      display: 'flex',
      justifyContent: 'flex-end',
      alignItems: 'center',
      padding: '3px 12px',
      borderTop: '1px solid var(--border-2)',
      borderLeft: '1px solid var(--border-2)',
      borderRight: '1px solid var(--border-2)',
      borderRadius: '6px 6px 0 0',
      background: 'var(--bg-elevated)',
    },
    '.cm-fenced-lang': {
      fontSize: '11px',
      color: 'var(--text-3)',
      fontFamily: "'JetBrains Mono', monospace",
    },
    '.cm-fenced-code-line': {
      borderLeft: '1px solid var(--border-2)',
      borderRight: '1px solid var(--border-2)',
      background: 'var(--bg-elevated)',
      padding: '0 12px',
    },
    '.cm-fenced-bottom': {
      borderLeft: '1px solid var(--border-2)',
      borderRight: '1px solid var(--border-2)',
      borderBottom: '1px solid var(--border-2)',
      borderRadius: '0 0 6px 6px',
      background: 'var(--bg-elevated)',
      height: '6px',
      marginBottom: '16px',
    },
    '.cm-frontmatter-widget': {
      background: 'var(--bg-elevated)',
      border: '1px solid var(--border-2)',
      borderRadius: '6px',
      padding: '10px 16px',
      display: 'block',
      marginBottom: '16px',
    },
    '.cm-frontmatter-row': {
      display: 'flex',
      alignItems: 'center',
      gap: '12px',
      padding: '3px 0',
    },
    '.cm-frontmatter-key': {
      color: 'var(--text-3)',
      fontSize: '12px',
      width: '110px',
      flexShrink: '0',
    },
    '.cm-frontmatter-key-input': {
      background: 'transparent',
      border: 'none',
      borderBottom: '1px solid transparent',
      outline: 'none',
      padding: '2px 4px',
      fontFamily: 'inherit',
      cursor: 'text',
    },
    '.cm-frontmatter-key-input:hover': {
      borderBottomColor: 'var(--border-2)',
    },
    '.cm-frontmatter-key-input:focus': {
      borderBottomColor: 'var(--accent)',
      color: 'var(--text-2)',
    },
    '.cm-frontmatter-value': {
      flex: '1',
      background: 'transparent',
      border: 'none',
      borderBottom: '1px solid transparent',
      color: 'var(--text)',
      fontSize: '13px',
      fontFamily: 'inherit',
      padding: '2px 4px',
      outline: 'none',
      lineHeight: '1.4',
    },
    '.cm-frontmatter-value:hover': {
      borderBottomColor: 'var(--border-2)',
    },
    '.cm-frontmatter-value:focus': {
      borderBottomColor: 'var(--accent)',
    },
    '.cm-frontmatter-add-btn': {
      display: 'block',
      marginTop: '6px',
      padding: '2px 8px',
      background: 'transparent',
      border: '1px dashed var(--border-2)',
      borderRadius: '4px',
      color: 'var(--text-3)',
      fontSize: '11px',
      cursor: 'pointer',
      width: '100%',
      textAlign: 'left',
    },
    '.cm-frontmatter-add-btn:hover': {
      borderColor: 'var(--accent)',
      color: 'var(--accent-2)',
    },
    '.cm-add-frontmatter-btn': {
      marginBottom: '8px',
    },
    '.cm-hashtag': {
      color: 'var(--accent)',
      cursor: 'pointer',
    },
    '.cm-list-bullet': {
      display: 'inline-flex',
      alignItems: 'center',
      justifyContent: 'center',
      width: '1ch',
      height: '1em',
      verticalAlign: 'middle',
      flexShrink: '0',
    },
    '.cm-list-bullet::before': {
      content: '""',
      display: 'block',
      width: '4px',
      height: '4px',
      borderRadius: '50%',
      flexShrink: '0',
      backgroundColor: 'var(--text)',
    },
    '.cm-bujo-event':     { backgroundColor: 'color-mix(in srgb, #4aa3ff 12%, transparent)' },
    '.cm-bujo-mood':      { backgroundColor: 'color-mix(in srgb, #56c596 12%, transparent)' },
    '.cm-bujo-idea':      { backgroundColor: 'color-mix(in srgb, #9d8dff 14%, transparent)' },
    '.cm-bujo-important': { backgroundColor: 'color-mix(in srgb, #ff5a5a 14%, transparent)' },
    '.cm-bujo-attention': { backgroundColor: 'color-mix(in srgb, #ffcc44 16%, transparent)' },
  },
  { dark: true },
)

export const darkHighlightStyle = HighlightStyle.define([
  {
    tag: tags.heading1,
    color: 'var(--cm-h1)',
    fontWeight: 'bold',
    fontSize: '1.35em',
  },
  {
    tag: tags.heading2,
    color: 'var(--cm-h2)',
    fontWeight: 'bold',
    fontSize: '1.15em',
  },
  { tag: tags.heading3, color: 'var(--cm-h3)', fontWeight: '600' },
  { tag: tags.heading4, color: 'var(--cm-h4)' },
  { tag: tags.heading5, color: 'var(--cm-h4)' },
  { tag: tags.heading6, color: 'var(--cm-h4)' },
  { tag: tags.strong, color: 'var(--cm-strong)', fontWeight: 'bold' },
  { tag: tags.emphasis, color: 'var(--cm-em)', fontStyle: 'italic' },
  {
    tag: tags.strikethrough,
    color: 'var(--cm-strike)',
    textDecoration: 'line-through',
  },
  { tag: tags.link, color: 'var(--cm-em)' },
  { tag: tags.url, color: 'var(--cm-em)' },
  { tag: tags.monospace, color: 'var(--cm-code)', fontFamily: 'monospace' },
  { tag: tags.quote, color: 'var(--cm-quote)', fontStyle: 'italic' },
  { tag: tags.list, color: 'var(--text)' },
  { tag: tags.meta, color: 'var(--cm-meta)' },
])
